### ISSUE TITLE
Base Character Speed

### ISSUE THREAD

**Issue by onurtirpan** [mipen/BannerlordTweaks#1]
Base character speed is way slower when compared even to the cheapest units in the game.

I was trying to achieve increasing it by CheatEngine but failed. Since you open-sourced your code, I gave it a shot but I'm super new to modding. I am experienced on C# but unable to gather the required info to achieve this.

If you could point me in the right direction, I'd love to adjust base character running speed and throw a PR.

Edit: Also, any hint to debug this without relaunching the game would be awesome.

Thanks for the mod!

**Comment by DaedalusTheFool** [comment]
Are you sure this is true? I thought this was because the main character has far more armor than most units so therefore is more encumbered?

**Comment by onurtirpan** [comment]
That could be true.

Starting a new game, getting a few basic soldiers gave me this idea. I do not wear heavy armor, it's what given to me during the game. 

Also, any character in the Arena is faster than my character too, and given the fact that their armor is probably way heavier than my starting armors; I still believe starting stats are a little bit unfair.

**Comment by OctaviusMods** [comment]
The starting Athletics skill for the player is just very low. Level it and you become as fast as anyone else.

**Comment by onurtirpan** [comment]
I know! This is why we need a tweak to start as fair as other NPCs. The purpose of this mod is to tweak unfair things. 

If you are suggesting to "play game a little bit to catch up with other players", then why use this tweak at all?

**Comment by Larkenx** [comment]
This could be a separate issue, but perhaps a quality new tweak would be raising the learning rate for all skills, and increasing the learning cap. It’s a bit unfair that you’re basically locked into not being able to level up other skills you might use but not have any skill points in imo.

**Comment by onurtirpan** [comment]
Agreed, I still think if we could implement a faster starting speed, it would be fair. I dig into the code but I was unable to understand how mods work for this instance. 

We have this code to get Athletics skill

SkillObject skillAth = SkillObject.FindFirst((x) => { return x.Name.ToString() == "Athletics"; });
 __instance.SetSkillValue(skillAth, 999);

But I am unable to figure out how to actually implement it in the proper file, override the right things etc.

**Comment by mipen** [comment]
I've added the increased skillcap idea and increased learning rate idea to my list of things to do, I think they would be good additions.
