### ISSUE TITLE
Initialising Error

### ISSUE THREAD

**Issue by pdbuchi** [mipen/BannerlordTweaks#101]
Hello, i have Initialising Issues with Bannerlord Tweaks.
Is this already known?

greetings!

![Bannerlord error](https://user-images.githubusercontent.com/65022921/81405730-87c12680-9138-11ea-8755-86b0e3b30cf5.PNG)

**Comment by mipen** [comment]
You are using an outdated version of the mod. Please update to the latest version according to the version of the game you are using (mod version 1.3.4 for the base game and mod version 1.4 for beta game version)
