### ISSUE TITLE
Mod options not appearing

### ISSUE THREAD

**Issue by Roseman36** [mipen/BannerlordTweaks#103]
When I downloaded the new version today after installing it I noticed in the main menu that the options are not appearing. Just blank screen with a search box and scroll bar.

**Comment by mipen** [comment]
Are you using ModConfigurationMenu?

**Comment by shpleep** [comment]
im having the same issue

**Comment by Roseman36** [comment]
> Are you using ModConfigurationMenu?

I am not, however I uninstalled mods incrementally until it came back. I can't remember the exact name of the mod but it was one that added a companion spec reset command to the console. 

Sorry for the late reply and thank you for getting back to me! Thanks for the mod!
