### ISSUE TITLE
error message at the start game runs anyway

### ISSUE THREAD

**Issue by cemcorbacioglu** [mipen/BannerlordTweaks#107]
![rijkFPM47x](https://user-images.githubusercontent.com/17089111/81486555-2f844480-925e-11ea-8a13-f30d75aa4632.png)

this message appears at the start but game starts. Also mod options are available in the game but (at least) party size modifier isn't actually working in the game

**Comment by mipen** [comment]
The mod version you're using is outdated. Please update to the latest version
