### ISSUE TITLE
No option in the ModLib menu on 1.3.0 to edit anything for the Mod

### ISSUE THREAD

**Issue by TheNog01** [mipen/BannerlordTweaks#108]
On the Main menu in Bannerlord, Bannerlord tweaks shows up in the Modlib options but their is no config options...

**Comment by AggressiveGR** [comment]
I had the same problem a couple of minutes ago. The mod says 
"Installation:Important: If you are updating the mod from a previous version, delete the old mod folder first."
What i did :
You will have to go into the document folder ("C:\Users\*UserName*\Documents\Mount and Blade II Bannerlord)... and delete the configs for a)ModLib b)ModSettings c)BannerlordTweaks. 
plus make sure you have the new version of Modlib.
Hope it works, Best regards Aggressive.

**Comment by mipen** [comment]
Are you using ModConfigurationMenu? If so, it should have an option to not overrite ModLib. ModConfigurationMenu causes issues with ModLib currently.

**Comment by mipen** [comment]
#117 Please read the comments in this linked issue for how to fix this.
