### ISSUE TITLE
No options in mod lib menu for new 1.30 version

### ISSUE THREAD

**Issue by Bunhtithnoung** [mipen/BannerlordTweaks#117]
As stated, the option doesn't even show up, other mods I have installed include Fixed launcher, attributes matter, developer console, fighting together relationship, improved garrisons, mod lib, settlement icons, B's faction armouries and killbanditsraiserelations.

**Comment by bcrotty** [comment]
@Bunhtithnoung I was having the same issue, but if you open the Mod Options, click on MBOptionScreen, and then uncheck Override ModLib Option Screen, that seems to have fixed it for me.

**Comment by mipen** [comment]
Just as bcrotty said. Mod configuration menu causes issues with modlib at the moment

**Comment by Bunhtithnoung** [comment]
![15894471020212392508647546994485](https://user-images.githubusercontent.com/65184141/81915420-765d9b80-95ca-11ea-8eb8-0bcf44e527af.jpg)
I don't have MB option

**Comment by mipen** [comment]
It is called Mod Configuration Menu now. If you have a mod which uses it, it is added to the game.

**Comment by mipen** [comment]
Download this mod:
https://www.nexusmods.com/mountandblade2bannerlord/mods/612
And make sure that it is the first loaded mod and ModLib is loaded directly after it.
Then you should have an option that looks like this:
![Capture](https://user-images.githubusercontent.com/8034500/81916308-01fd1980-9617-11ea-86b6-974e7d130d0a.PNG)
You should get an option like the one circled. Make sure that the override option is unchecked.
Unfortunately the creator of Mod Configuration menu thinks it's good practice to mess with ModLib, which creates errors for people trying to use both.

**Comment by Bunhtithnoung** [comment]
Okay awesome thank you so much!
