### ISSUE TITLE
No mod options in game

### ISSUE THREAD

**Issue by Anhur1111** [mipen/BannerlordTweaks#126]
In menu i can't change a mod options, its empty
![11111](https://user-images.githubusercontent.com/65346221/81932514-36a7ab80-95ec-11ea-9850-2a17ed9e8d18.png)
![22222](https://user-images.githubusercontent.com/65346221/81932524-3a3b3280-95ec-11ea-847b-d8e462126d3a.png)

**Comment by mipen** [comment]
Please read the comments listed here for fixes: https://github.com/mipen/BannerlordTweaks/issues/117
