### ISSUE TITLE
Throws Report but doesnt crash.Tweaks not applying in game

### ISSUE THREAD

**Issue by AbradulfLincler** [mipen/BannerlordTweaks#129]
![Screenshot (8)](https://user-images.githubusercontent.com/65383584/82011096-94161980-9639-11ea-882e-697ce6a9542d.png) Heres report being shown

![Screenshot (9)](https://user-images.githubusercontent.com/65383584/82011183-ca539900-9639-11ea-90d0-6908fca26801.png) "Sorted" mod list Pic 1 Using latest 1.3.1 FIxed Mod launcher

![Screenshot (10)](https://user-images.githubusercontent.com/65383584/82011246-fff88200-9639-11ea-87de-37cbfecd02b7.png) "Sorted" mod list Pic 2 Using latest 1.3.1 FIxed Mod launcher

My guess is its Sorting something incorrect, or i have a mod thats having dependency issues. Still very new to this. 1st actual bug report after 300 hours of Bannerlord "total" and all mainly using mods and many of them. I consider myself lucky being this is first time i needed to post to see if anyone knew anything that can assist me. Hoping i can move few mods around, or Just find the one/ones doing the Crash report.

Please Feel free and dont hold back on letting me know on what im doing wrong or insufficiently when it comes to posting issues or bugs.Always looking to improve if possible. And would love to get this fixed, Im stressing without my fix of Butterlord today lol

**Comment by AbradulfLincler** [comment]
So i feel stupid, i read a post down from this a few days ago talking about the castle building tweaks, so i disabled any Building tweak the mod has, and started with no report this time. Testing now, so im assuming this can be deleted. I will investigate if im able to do so or not

**Comment by mipen** [comment]
This is happening because you are using the incorrect version of the mod. You are using the version for the beta branch of the game. If you are still playing on e1.3, download the 1.3.6 version of the mod.
