### ISSUE TITLE
Crash when moving on world map

### ISSUE THREAD

**Issue by maiestatis** [mipen/BannerlordTweaks#140]
Game crashes when I attempt to move on the world map.

Other mods I have:
- community patch (https://www.nexusmods.com/mountandblade2bannerlord/mods/186)
- launcher fix (https://www.nexusmods.com/mountandblade2bannerlord/mods/205)
- modlib

I've tried disabling listed mods, it does not solve the problem. I've also disabled this mod only, and it seems to fix the problem.

All files are unblocked, mods are ordered.
Crash message:

![bannerlord_crash](https://user-images.githubusercontent.com/65546204/82214379-09256f80-9916-11ea-94fb-42a38d3a4075.png)

**Comment by mipen** [comment]
Thanks for letting me know. I've uploaded a new version which fixes this (version 1.4.5)

**Comment by maiestatis** [comment]
Hey, thanks for the quick response. I updated the mod, and unfortunately the issue persists.

Here's the new message: 

![image](https://user-images.githubusercontent.com/65546204/82307147-3dee0100-99c0-11ea-9459-c7e82b22a6f5.png)

**Comment by mipen** [comment]
I don't think the mod updated properly for you. Make sure to delete the mod folder before installing the new version. If you are using vortex, try installing the mod manually

**Comment by maiestatis** [comment]
You're absolutely right. I messed up and installed the old version again. Sorry! Works fine now.
