### ISSUE TITLE
Config.xml file missing

### ISSUE THREAD

**Issue by BongLenis** [mipen/BannerlordTweaks#141]
*\zzBannerlordTweaks\ModuleData\Loadables\config.xml is missing.
Have had issues with the mod crashing before and looked for a solution but there was no file to edit. Is this file supposed to be created on the first launch with this mod?

**Comment by mipen** [comment]
The config files is located in My Documents/Bannerlord/Config/Bannerlord Tweaks

Are you receiving an error message when the game crashes?

**Comment by BongLenis** [comment]
I did get a crash error but I cant seem to be able to locate the crash log.
