### ISSUE TITLE
mod options for bannerlord tweaks empty screen

### ISSUE THREAD

**Issue by ygirard** [mipen/BannerlordTweaks#143]
All in the title. Bannelord tweaks section of mod option is empty except 'revert to default'. If that is of any relation , I should mention that so is 'modlib' mod option screen. 

Edit: the mod must be working since I get detailled bug report on crashes.
Edit: vortex install or both tweaks and modlib 
Edit: basic things I tried that did nothing visible: changing load order to have modlib first , remove MBoption called 'override modlib screen' ,  reinstall the two mods.

**Comment by ygirard** [comment]
I'm now trying to see if I can somehow edit the options in a file. I did find in documents .... configs/zzBannerlordTweaks/  but this dir is empty (related to the issue or normal situation ?) . I could try to dive into the source code. I'm happy with this mod default options except for the hideout ones. I want an hideout to be this tactic carefull experience and not me crushing some unaware bandits who did not notice 100 guys coming up :)

**Comment by ygirard** [comment]
ok I have the issue , not the solution. I used "detailled character creation" who uses this MBoption that somehow overrides modlib and this created a conflict somewhere. Probably a class call messed up , I've no clue if there is way to have them both work together. Probably you guys can understand better than me. I guess I'll just use detailled char creation only at startup for now

**Comment by mipen** [comment]
Try installing the mod configuration menu mod and make sure it is the first mod loaded, then load modlib directly after it. That usually fixes any incompatibility issues between mboption and modlib

**Comment by ygirard** [comment]
thank you I will try it out. So installing mboption explicitely is your advice , right ?

**Comment by ygirard** [comment]
So for anyone encountering this issue arriving here. "Detailed creation" requires the "mod configuration menu" (probably other mods do too) and in Vortex you *must* use the 'auto-sort' option in the load order otherwise you get all kind of crashes because mods try to call on non-existing elements. I know I should post on the github of this mod ,at least this info is somewhere. 
![image](https://user-images.githubusercontent.com/17650235/82753635-4a5ec900-9dc7-11ea-916c-20012f74ffb0.png)

**Comment by ygirard** [comment]
and btw : "fixed"
