### ISSUE TITLE
Party size bonus from leadership/steward goes wild

### ISSUE THREAD

**Issue by RaeTheLynn** [mipen/BannerlordTweaks#151]
Wish I had some form of repro steps for you. I have seen this happen on multiple saves with differing mod setups.
For some reason the calculation for the leadership & steward party size bonuses continually increases, even beyond 100%. Sometimes restarting the entire program resolves the issue.

I have a sneaking suspicion that a multiplier value is getting incremented that shouldn't when one of these skills levels up. I will keep an eye and try to get more information for you.

**Comment by billw2012** [comment]
I have repro steps:
1. Load into a game
2. Quit to menu (don't save, just quit)
3. Load the same game again, and note that the bonus is now applied (I guess) twice.
Repeat as many times as you want for infinite party size!

**Comment by RaeTheLynn** [comment]
Can confirm the repro steps, thanks @billw2012 !
