### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mgemperl** [mipen/BannerlordTweaks#16]
Have you mentioned the terms under which you're making this code available someplace? As far as I can tell, it's still all rights reserved.

I'd kinda like to use your ModLib code in a mod I'm working on, if you're willing to release it for others to use.

**Comment by mipen** [comment]
At the moment all rights reserved until I get around to sorting everything out. I will be separating ModLib out into a separate mod to act as a general modders resource, but hoping for a fix to mod stability first. Currently there is a hard limit of 16 active modules (including the official ones, so 11 downloaded mods) and load orders aren't very reliable.

You'll definitely like the next update to ModLib though, it includes an easy to hook into mod configuration menu!

**Comment by mgemperl** [comment]
Ooh, I really am looking forward to that, then. Thanks for all the helpful utilities. The detailed crash reporting is already a great help. 

The tweaks are nice too, of course.

**Comment by Jayshua83** [comment]
>  Currently there is a hard limit of 16 active modules (including the official ones, so 11 downloaded mods) and load orders aren't very reliable.

I keep reading this but I have over 30 mods running and working together just fine! Also using the Fixed Launcher which handles load order just fine!

**Comment by Tyler-IN** [comment]
I don't think there ever was a hard limit of 16 mods, not sure where that rumor came from...

**Comment by Aberro** [comment]
You're kinda violating your own license to ModLib, heh.
