### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by ajvr** [mipen/BannerlordTweaks#21]
Thanks for making this mod, the settings menu is excellent! I've been making a number of tweaks of my own but not wanted to release a whole mod, so I figured it was best to just submit them to you for inclusion; especially because this is likely the best way to get them distributed.

I don't want to create extra work for you or propose more changes if you wanted to maintain this primarily as a personal project, so it'd be good to know where you stand on contributions.

**Comment by mipen** [comment]
Yeah, I'm definitely open to contributions. Maybe not anything major as I like to be able to read it and know how it works before merging - helps with maintaining down the line.
Now that I've finished working on the settings menu, I'll be merging open pull requests. I do appreciate the help!

**Comment by ajvr** [comment]
Happy to help you out! Thanks for your work
