### ISSUE TITLE
Github releases

### ISSUE THREAD

**Issue by agates** [mipen/BannerlordTweaks#23]
Would you consider creating releases on Github, for those who would like to use the Watch notifications and/or download the release files here?

**Comment by Jayshua83** [comment]
This would be nice, since it appears GitHub is updated more often then Nexus!

**Comment by mipen** [comment]
Yeah I can do this for future updates. Note that the commits here are from development of the mod and shouldn't show that it is more up-to-date than the nexus version. I upload to the nexus when I am happy the mod is in a stable state, and it would be the same version that is added to the releases section here.
