### ISSUE TITLE
Hideout Battle Tweaks checkboxes description inverted

### ISSUE THREAD

**Issue by kaeltis** [mipen/BannerlordTweaks#24]
It seems that the descriptions of the Hideout Battle Tweaks checkboxes are inverted to their actual function.

They say 
"Continue Hideout Battle on Player Death" and "Continue Battle on Losing Duel"
however the options in the xml are called
"LoseHideoutBattleOnPlayerDeath" and "LoseHideoutBattleOnPlayerLoseDuel"

Having them unchecked (false) continues the battle, having them checked (true) makes you lose on death, so the names of the options in the xml are correct.

**Comment by ajvr** [comment]
This got fixed in 05eb9dd82bb99bc9c57d033d1bc965e44fdb6d99 so should be changed when there's another release

**Comment by kaeltis** [comment]
Thanks!
