### ISSUE TITLE
Tourneys Crashing

### ISSUE THREAD

**Issue by Dasgamerman** [mipen/BannerlordTweaks#27]
Got the mod setup and working. But everytime I do any Arena fights it crashes and the image below shows what the warning says.

![crash](https://user-images.githubusercontent.com/63386489/78858176-74f3ee80-79e0-11ea-96ac-6eae00c09c3f.png)

**Comment by mipen** [comment]
You aren't using the latest version. Download the latest version, delete the folder mod folder from your modules folder and install the latest update (1.1.1)
