### ISSUE TITLE
Slider Issues

### ISSUE THREAD

**Issue by Jayshua83** [mipen/BannerlordTweaks#29]
Not sure if this is something you can fix in your mods GUI or if it is from the native UI?

But certain slider bars won't change number by number or in full numbers... Instead it skips numbers and doesn't allow certain numbers to be reached.

**Comment by mipen** [comment]
This might be a vanilla issue.

Some of the bars are set to include decimal places as the setting they represent needs decimal places. 

If there is a large range to choose from (say 0 - 100) it will make the hit spot for each number quite small.

I am going to add an option to type in the value that you want to make it easier to select the settings.
