### ISSUE TITLE
0 Exp for Troops in simulated Battles

### ISSUE THREAD

**Issue by Merkyr1al** [mipen/BannerlordTweaks#30]
I simulated battles with a 100 Looters or more and my Troops are getting barely any upgrades. Like 1 upgraded Troop for 100 Looter simulated Battle. Before the update it was way more upgrades

**Comment by Merkyr1al** [comment]
I just copied bug report message from nexus. Check it and you will see that there are some people who have this trouble. I tried reinstall, doesn't help.

**Comment by mipen** [comment]
This was a bug in a previous version. It should be fixed in update 1.1.3
