### ISSUE TITLE
2nd Mod Options

### ISSUE THREAD

**Issue by Jayshua83** [mipen/BannerlordTweaks#32]
Any reason why I would have a 2nd Mod Options at the bottom of my Main Menu but its not usable or clickable?

**Comment by ajvr** [comment]
Do you have another mod installed with a Mod Options menu? I think AutoTrader might

**Comment by Jayshua83** [comment]
Ah. Figured it out... I finally got access to the button after removing the "Just Let Me Play" mod. It had pushed the button down and I couldn't access it. It appears to be from the Community patch! I wish they were using the same system you were! :(

**Comment by Jayshua83** [comment]
https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/61

https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/97
