### ISSUE TITLE
Settings don't persist when mod is updated.

### ISSUE THREAD

**Issue by tizubythefizo** [mipen/BannerlordTweaks#33]
Since the mod settings file is included in the actual mod, every time the mod is updated existing settings will be wiped out. It's also not safe to manually back them up and replace over the settings file when updating since the settings themselves may change.

I would strongly recommend creating and storing settings in game's documents folder somewhere (Users\<username>\Documents\Mount and Blade II Bannerlord), maybe in the existing config folder, or a created folder.

That way they'll persist across updates, and if there are breaking changes to the structure you can handle updating from within the mod.

**Comment by mipen** [comment]
Thanks for the feedback! The next update will include settings being saved to the Documents' Config folder so the settings persist.
