### ISSUE TITLE
Bug where Lords become a ball of graphics.

### ISSUE THREAD

**Issue by Twitchedout1** [mipen/BannerlordTweaks#36]
There's a bug where and other Lords become a ball of stretched graphics. I don't know if its a certain armor piece that is doing it or what, but it takes about a second to "render" the ball. [https://steamcommunity.com/sharedfiles/filedetails/?id=2054933402](url) This is a image from a tournament that I did. I started a new run and saw it. I had the mod before this run and didn't notice it then.

**Comment by mipen** [comment]
Poor Caladog :(

This isn't caused by Bannerlord Tweaks, I don't touch anything to do with graphics. It is probably a Native bug if you don't have any other mods that deal with graphics changes.
