### ISSUE TITLE
Any plans of releasing ModLib as a standalone mod?

### ISSUE THREAD

**Issue by nefdulin** [mipen/BannerlordTweaks#38]
Are there any plans of releasing ModLib as a standalone mod?

**Comment by brandonm4** [comment]
Was about to ask the same question.  +1 for the request.  
I tried to run just the ModLib submodule portion by itself and was getting an DatabaseSettings error on load.  My mod was still able to register it's settings class however.

**Comment by nefdulin** [comment]
i am having issues when trying to load both my mod and bannerlordtweaks. i think it would be much better if there is another repo dedicated to the development of modlib and a standalone release on nexus so we can set modlib as a requirement for our own mods.

**Comment by mgemperl** [comment]
mipen briefly mentioned plans for that here: #16

**Comment by mipen** [comment]
I'll be making ModLib its own mod in the next update for Bannerlord Tweaks. It'll have its own repo too. I'll write up the wiki for it as well, so that it is easy to hook into it and use it.

**Comment by nefdulin** [comment]
thanks!
