### ISSUE TITLE
double siege equipment for defenders?

### ISSUE THREAD

**Issue by R4MPZY** [mipen/BannerlordTweaks#41]
Hey all, i'm not sure if this is a bug or an intended feature but i couldn't find it anywhere in the mod description or mod options.

When i enable this mod any castle or city i siege seems to have double the siege equipment on the same slot.

For example i start a siege and only see 4 scorpions so i rush ram and towers and start battle, however once in the battle they have 4 scorpions AND 1-2 onagers aswell?

If i start a siege and i see they have onagers i build a trebuchet instead and wait until i have 3 to start bombarding the city ( campaign map not in battle scene ) and when they destroy an onager there is a scorpion in its place ?

I checked this with the mod turned off and there is no issue then. Does it maybe have something to do with the harmony file? Another mod i am using is using that aswell.

I am using the mods;

AttributePerLevel
CharacterTrainer
zzBannerlordTweaks.

**Comment by mipen** [comment]
Hey there, I'm not sure what could be causing this. I wouldn't think anything in the mod would be doing it as the mod aims to actually slow down siege engine construction. Harmony isn't the cause, it is simply the code library that we use to patch the game's code.

It is worth noting that once a siege engine is built, it can be put into a 'stockpile'. If you click on it after it is built, there is an option to do this. Perhaps this is what is happening - the AI is putting siege engines into the stockpile and then during the battle there are more slots for them to use than on the campaign map.

**Comment by R4MPZY** [comment]
Yeah that may be possible, its only weird that as a player you can only have 4 slots as attacker or defender while the AI has a possible 8 slots, 4 scorpions and 4 onagers ( which can snipe a ram without missing a single shot xD )
