### ISSUE TITLE
ModLib - bug I think

### ISSUE THREAD

**Issue by brandonm4** [mipen/BannerlordTweaks#43]
In FileDatabase.cs - SaveToFile

The first !Directory.Exists (line 72) will fail and throw an exception if the module config folder does not exist.  Later on - line 89 is where you create the folder.  

I change the throw exception to a Directory.CreateDirectory and settings folder and config file were generated on first run (which I think is your intended behavior). 

Try testing by removing your Config folder from your documents.

**Comment by mipen** [comment]
Thanks for letting me know. I haven't finished implementing that change as I have gone away for Easter. Will fix it when I separate ModLib into its own mod in the next update.

**Comment by mipen** [comment]
ModLib is completed now and the issue was fixed.
