### ISSUE TITLE
Missing mod options.

### ISSUE THREAD

**Issue by Lazyshot43** [mipen/BannerlordTweaks#44]
This may be a problem on my end but, mod options are not on my main menu screen, I can not find anything anywhere on why this might be, spent the better part of an hour searching and found myself here.  any ideas for me ?

**Comment by Xanhou** [comment]
Did you enable the mod in the launcher?
In the launcher where you also pick between singleplayer and multiplayer, there is also a button for mods. Make sure the mod is checked in that menu.

**Comment by Lazyshot43** [comment]
yeah , the mod is working for me, I just cant find the mod options to configure it like it says.

**Comment by seedlessbuns** [comment]
Same issue here

**Comment by mipen** [comment]
Have you checked that things are being loaded in the correct order?
