### ISSUE TITLE
Not getting Smithing Exp?

### ISSUE THREAD

**Issue by lukylemmie** [mipen/BannerlordTweaks#45]
Hello,

Thanks heaps for this great mod.

I don't know if it is because of the new beta branch e1.1.0 but I am not getting smithing experience if I use your mod (both the flat experience multiplier setting or your default exp gain setting).

I have tried with your mod off and I get smithing experience.

Regards,
Lem

**Comment by mafiaf** [comment]
Hi,

I seem to have the same issue as Lukylemmie.
The only way of getting smithing XP is by smelting products down. Even then it's only 3-4 xp per smelt.

**Comment by KaiSchwier** [comment]
Yeah same here, also Steward stopped leveling, haven't tested whether it works without the mod though.

**Comment by IonicDovah** [comment]
I may have found a fix for now, this works for trading but I was having the same issue for both trading and smithing (Havent tested it out with smithing yet). Disable the actual category Hero Skill Experience Tweak then reload game, since by default the category is active but not the subset itself. It should start gaining xp like normal again :)

**Comment by bladesofwill** [comment]
This is affecting stewardship xp as well. Disabling the entire Hero Skill Experience Tweak section as IconicDovah suggested fixed the issue.

Playing on the beta branch e1.0.11

**Comment by WolfricThorsson** [comment]
Ironically, I seem to have had the complete opposite problem - I just installed the mod, went to refine some material, and IMMEDIATELY gained 1019 levels in smithing!
![Smithing Bug](https://user-images.githubusercontent.com/63791281/79454716-9efe6f80-7fe3-11ea-9929-d2ee72d950c1.JPG)

**Comment by mipen** [comment]
Thanks for the heads-up. I have disabled the skill experience multiplier for now until I have time to test whether it is needed in the newest game version.
