### ISSUE TITLE
Saved Game Crash

### ISSUE THREAD

**Issue by dekarian** [mipen/BannerlordTweaks#46]
Hi, thanks again for the great mod. Can't play the game anymore without it. As of e.1.0.11 (main branch, not beta), my saved game crashed on load-up. Using the latest version of BannerlordTweaks (1.1.3). This is the crash log that popped up:
https://imgur.com/a/afLgToS

I saw a similar issue with someone on nexus mods. Their crash log:
https://imgur.com/CKr3j9s

**Comment by Rabbitt04** [comment]
Getting this same report too with only a difference in the numbers.

Can start a new game fine and play without any issues but on trying to reload a save this same message pops up.
I'm using the most recent upload and stable 1.1.0 of Bannerlord

**Comment by mipen** [comment]
I've added a whole lot of null checks to the method that causing the error. Hopefully it is fixed now and won't cause issues in the future.
