### ISSUE TITLE
Very little trade/smithing skill gain?

### ISSUE THREAD

**Issue by IonicDovah** [mipen/BannerlordTweaks#48]
Thank you for this fantastic mod, i have run into a little issue that is hindering me in the early game. That is I am gaining no trade xp or very little for making trades. I have confirmed this with stopping the mod then going back into the save, the very same trade gave me 5 levels while with the mod it gave me approx 50xp.

Also it seems to be effecting smithing as well but i have not tested that out as of yet to see if that is having the same issues but with smelting down a few things already I could not see any xp gain when usually native would see some kind of level change

**Comment by IonicDovah** [comment]
Just a follow up on my post here, I ended up locating at least what subset is causing it, it seems to be the Hero Skill Experience Tweak. I had the category active but not the actual Experience Tweak active so unsure but disabling the Hero Skill Category itself seems to have fixed it :)

**Comment by mipen** [comment]
Thanks for the heads-up. I have disabled the skill experience multiplier for now until I have time to test whether it is needed in the newest game version.
