### ISSUE TITLE
Scouting Exp Bug / hideouts

### ISSUE THREAD

**Issue by MobyDackdaReal** [mipen/BannerlordTweaks#49]
When I spotted a Hideout, I instantly got my scouting level points on 1113 :P was on the version from nexus mods, downloaded it today.

**Comment by MobyDackdaReal** [comment]
aaah no I think I know whats bugged, when u assign a role in the clan, quarter master etc, u get like 1000 exp if u do it succesfully ( lol )

**Comment by bcrotty** [comment]
This happened for me with smithing experience. I went up 1000 or so levels when I refined something.

**Comment by bcrotty** [comment]
This is still happening for me (~1000 levels in smithing when I refine) with 1.1.4. The problem goes away when I disable the hero experience tweaks.

**Comment by MobyDackdaReal** [comment]
ty for saying so

**Comment by mipen** [comment]
Thanks for the heads-up. I have disabled the skill experience multiplier for now until I have time to test whether it is needed in the newest game version.
