### ISSUE TITLE
Workshop limit does not work.

### ISSUE THREAD

**Issue by Dextradamusz** [mipen/BannerlordTweaks#52]
I'm a n00b at programming or troubleshooting, so you know.

After setting the tweaks for workshops to it's maximum 10 per default + 3 per clan rank, and restarting the game afterwards to apply said changes, and there after checking in the tweaks setting that it remained so. 
I found that while in the game itself it is not applied, using the native settings instead (I think).
My clan rank is 5 and can only have 7 workshops appearantly. while it should be 25 if I am not mistaken.

**Comment by TheGodfatherRus** [comment]
I have the same issue. I`ve also had a {V`s no workshop limit}, but it doesn`t work with Bannerlord Tweaks mod

**Comment by mipen** [comment]
Sorry it has taken so long to reply to this. I have tested and it works in the latest version. I'm not sure what was happening here, but it no longer seems to be broken.
