### ISSUE TITLE
Smithing jumps up to lvl 1023

### ISSUE THREAD

**Issue by bobokox** [mipen/BannerlordTweaks#53]
Hey!
First of all, thank you very much for this mod!

I've already reported this in the Nexus discussions.
I updated the game and the mod + modlib. Since then I didn't get xp for smithing actions anymore. This was because I disabled the Hero experience tweak option. After enabling it was gaining xp again but on the next level up of the skill I suddenly was level 1023 in smithing (+838 levels).
This seems to effect smithing only, as far as I can tell. I succesfully leveled up tactics +1.

Hope there will be a fix soon - i really love this mod!

thank you!

**Comment by mipen** [comment]
Thanks for the heads-up. I have disabled the skill experience multiplier for now until I have time to test whether it is needed in the newest game version.
