### ISSUE TITLE
Crashes bannerlord launcher when installed

### ISSUE THREAD

**Issue by Savagekingofaoterora** [mipen/BannerlordTweaks#55]
When Bannerlord Tweaks is placed into the "Modules" folder the launcher refuses to open. All other mods work (I have 23)

**Comment by CratylusCO** [comment]
I had this problem with the default launcher as well. I downloaded the fixed launcher and it will open but I can't activate this mod.

**Comment by mipen** [comment]
There is apparently a bug with the default launcher which causes issues if there are more than 16 modules in the Modules folder (counting Native ones). Try running the game with only modlib and bannerlord tweaks installed. If it runs, try installing all mods and using the fixed launcher mod.
