### ISSUE TITLE
Skill Point glitch related to clan role

### ISSUE THREAD

**Issue by deswer4** [mipen/BannerlordTweaks#56]
I love this mod so much, and thank you so much for making it and keeping it updated.

Whenever my clan role is selected as surgeon and I gain a skill point in medicine, I gain about 1000 skill points in medicine. Similarly, when I am quartermaster, and I gain a skill point in stewardship, I gain about 1000 as well. I have tested this and confirmed it in both the stable and beta builds. 

I've seen people having a similar problem with engineering or smithing, but I haven't had the opportunity to test that yet.

**Comment by Idleness76** [comment]
I can confirm it happens with Scout and Smith skills as well too.

**Comment by Dextradamusz** [comment]
I have had the exact opposite where when you select a role it stops gaining skillpoints in the related skills.

**Comment by themoland** [comment]
I have just had this happen to me aswell
![20200419124735_1](https://user-images.githubusercontent.com/63955204/79685947-d1ef7000-823c-11ea-97d2-66337a5e7ed4.jpg)

**Comment by Idleness76** [comment]
1023 is the magic number.  Every time this happened that was the skill level.

**Comment by mipen** [comment]
Thanks for the heads-up. I have disabled the skill experience multiplier for now until I have time to test whether it is needed in the newest game version.
