### ISSUE TITLE
Skill point glitch - One handed and athletics jump to 1023

### ISSUE THREAD

**Issue by TubOfButter77** [mipen/BannerlordTweaks#57]
This mod adds a lot of cool features so thank you! However, I noticed that after the 1st round of a tournament my one handed and athletics skill jump to 1023 out of no where. Thank you!

**Comment by SamSherrill** [comment]
2 of my companions had this happen. The skills that jumped were the the ones tied to their roles in the party (surgeon & scout).

**Comment by themoland** [comment]
this happend to me just now 
![20200419124735_1](https://user-images.githubusercontent.com/63955204/79685969-ee8ba800-823c-11ea-81f3-c912b86b8ca6.jpg)

**Comment by mipen** [comment]
Are you using beta 1.2? The mod currently isn't tested with beta 1.2. There was also a change in how skill experience was done. The latest version of the mod has skill experience multipliers disable for now.

**Comment by SamSherrill** [comment]
Hi Mipen, thanks for your work on this! Modding is probably a mostly thankless job, and probably a lot of work, especially a mod as complete as yours. I love the mod!

No, I'm not on the beta. I use Fixed Launcher & ModLib, along with a few other mods. The only one that I think might be interacting with yours is the Attribute per Level mod. However, I've had that alongside Bannerlord Tweaks for a week or more, and this hasn't been a problem before.
