### ISSUE TITLE
Start Up- files failed to load

### ISSUE THREAD

**Issue by Spaten178** [mipen/BannerlordTweaks#59]
so this mod is great but recently i encountered a problem that when launching the game it would fail to load the mod files, and this error is displayed thanks to moblb

an error occurred whilst trying to load files for module:
zzBannerlordTweaks

exception
an error occurred while filedatabase was trying to load all files for module zzbannerlordtweaks

Exception
An errer occurred whilst loading file
../../module\zzbannerlordtweaks\module\loadabkes\settings.bannerlordtweakssettings.xml

invalidoperationexception
there is an error in xml document (75, 74).

formatexceptionexception
input string was not in correct format

strack trace
at modlib.filedatabase.loadallfiles_string modulename)
at modlib.filedatabase.initialise(string modulefoldername

the game doesn't crash and still loads and all other mods installed load as normal no matter what order I put it in

I have deleted all other mods from the game and still get that error

the mods presumes to appear in the game in it own place and when editing you settings it says to restart for them to take affect and when that does the error still appears plz help

**Comment by mipen** [comment]
Delete the mod folder and reinstall the latest version. It looks like there was an error in the settings config file. Deleting it will fix the issue.
