### ISSUE TITLE
Crash on QuestPartySizeHelper

### ISSUE THREAD

**Issue by ChildServices** [mipen/BannerlordTweaks#60]
Happens when the day ticks over. Only reason I posted this to you here is because it does say "BannerlordTweaks.Patches"
![Capture](https://user-images.githubusercontent.com/28391846/79690172-6210d200-829c-11ea-9004-89daedd07307.PNG)

**Comment by mipen** [comment]
Thanks, I've added a lot of checking to try and make sure this doesn't happen again.
