### ISSUE TITLE
1.2.0 - Experience for Assigned Clan Role

### ISSUE THREAD

**Issue by SirBrainwash** [mipen/BannerlordTweaks#63]
Companions are not receiving experience for the skill related to their assigned Clan Role (scouting, medicine, steward, engineering). I tested this on the 1.2.0 Beta and 1.1.1 Release using the 1.1.5 build of BannerlordTweaks. However, companions will receive experience in these skills while in their own party.

The only mods enabled were:

Developer Console;
ModLib;
BannerlordTweaks

Happy bug hunting!

P.S. I did test this in Native with the Developer Console enabled and there was no issues with Companions gaining experience for their assigned Clan Role.

**Comment by donkybro** [comment]
I have found the exact same, including the fact that the main character does not gain experience for the role they are assigned either.

**Comment by SirBrainwash** [comment]
Tested all of the same parameters using the 1.1.6 BannerlordTweaks and the issue of companions and the player character not gaining experience in their assigned clan roles has been fixed.
