### ISSUE TITLE
Smithing Crash - Still Broken

### ISSUE THREAD

**Issue by SvendTheViking** [mipen/BannerlordTweaks#64]
Even after the latest update my game crashes when entering smithing

**Comment by Mahsery** [comment]
Even disabling smithing module on mod settings don't work. Game instantly crashes after clicking smithy.

**Comment by mipen** [comment]
Are you using beta 1.2? You will need to disable the auto-learn parts from smelting and hide locked items from smelting view tweaks.

Those tweaks currently aren't compatible with beta 1.2

**Comment by Mahsery** [comment]
Yes you are right, after reading the other thread disabeling hide locked items solves the problem. Auto-learning parts works okay though.
