### ISSUE TITLE
skill level 1023 bug solution?

### ISSUE THREAD

**Issue by founta** [mipen/BannerlordTweaks#66]
From 1.0 -> 1.1/1.2 they changed the Hero.AddSkillXp function to take a float. It used to take an integer. However, on line 20 of Patches/HeroPatches.cs in the definition of that Harmony Prefix function, you still assert that xpAmount is an int.

The casting from float -> int probably results in the massive integer value breaking the amount of xp earned. Switching the int in the function definition to a float might fix the issue. I would submit a pull request after verifying that this fix indeed works, but I cannot get the mod to properly build with visual studio.

Let me know if this does/does not help. I've also PM'ed you the same information on the Nexus forums.

Thanks.

**Comment by mipen** [comment]
Thanks. I've disabled the skill experience multiplier for now, will look into implementing it again if I can find the time to test a balanced way of doing it. That is good information though! As it is, patches don't give a warning if something in the game's dll files change. Becomes a process of checking every patch is still current.
