### ISSUE TITLE
siege engines stuck on 0% while besieging

### ISSUE THREAD

**Issue by purpIefiction** [mipen/BannerlordTweaks#69]
mod list in respective order:
modlib
bannerlordtweaks
autotrader
daytimehideouts
dev console
killbanditsraiserelations
mbfastdialogue
partymanager
smithing hide unknown
theeshallstserve

gave myself engineering through console to test a siege, the engines are stuck at 0% and i cant build eventhough i have 200+ siege.
this mod is the only thing changing siegeengine build speed

**Comment by PieroSgri** [comment]
Are you sure the camp is ready ? When sieging the camp must be buit first (the progress bar you see on the screen) after that any siege stuff you queued start gaining building progress.
