### ISSUE TITLE
CTD - NullReferenceException

### ISSUE THREAD

**Issue by Retrofly** [mipen/BannerlordTweaks#71]
Stack trace:
![image](https://user-images.githubusercontent.com/64139895/79976472-95b64c80-8494-11ea-80ee-9a12fd62f81c.png)

Didn't generate a crash log, nothing in the rgl logs.

Initial crash happened midgame after about 20 days of a new campaign. Now crashes on startup with the above. Running version e1.2.0

**Comment by mipen** [comment]
This should be fixed in the latest version of the mod.
