### ISSUE TITLE
modlib and Tweaks not compatible

### ISSUE THREAD

**Issue by Bastonnade** [mipen/BannerlordTweaks#73]
Hi there ive been using Tweaks alone and works great, but ive started to want to add more mod into the game and they required Modlib standalone. so i installed it and since it made my game crash on startup. so i did some digging to pinpoint why im crashing and from what ive seen, have modlib alone, games run fine and as soon as i put back bannerlord tweaks back in the file. Game is crashing.. I believe is because your mod run its own modlib and modlib settings and because of the 2 ( standalone and your built-in modlib) make the game crash. Is it possible to have a version of bannerlord tweaks that runs off the standalone version instead of the files within tweaks?

**Comment by printer16** [comment]
Hey, 

The mod only works with ModLib. When you install Modlib and Tweaks the mod (Tweaks) works as intended. Currently, assuming you are on 1.3, tweaks is not functioning which explains the anomalous behavior when you use tweaks without Modlib.

Hope this helps.

**Comment by Bastonnade** [comment]
I might have explained myself incorrectly.. I used bannerlord tweak without modlib installed. Worked like a charm.. From what have figured is that since you add the modlib file and settings within bannerlordteeak folder itself i didnt had to install modlid seperatly.. But if i wanted to play with other mods that needed modlib anyway.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Bastonnade** [comment]
And yes i have the 1.1.3 version.
________________________________

**Comment by mipen** [comment]
Bannerlord Tweaks requires ModLib in order to function.
