### ISSUE TITLE
Compatibility issue with saves under beta Patch 1.3

### ISSUE THREAD

**Issue by RamonMarius** [mipen/BannerlordTweaks#77]
Firstly, thank you so much for creating this indispensable mode!
Unfortunately, at least after opting into beta patch 1.3, in my case the game crashes upon loading any old saves.

And yes, I updated to the latest version and installed the modlib, which also appears before tweaks in the list of  mods. The only other mode I am running is the developer console, a combination that did not create any problems beforehand.

Are there any plans to create a version that is compatible with the new beta Patch ?

**Comment by Nickitus** [comment]
Do as follows: Smelting stamina tweaks - off. Save in new slot, then reload from that slot and enjoy

**Comment by joshimoo** [comment]
Here is the pull request with fixes for beta 1.3
#75

**Comment by mipen** [comment]
Beta version is (finally) done.
