### ISSUE TITLE
Issue with beta 1.3

### ISSUE THREAD

**Issue by jimbitol** [mipen/BannerlordTweaks#81]
Hello! thanks for your time invested on this mod, it is great, very useful, I wanted to report this issue , and feel free to take the time to have a look.

THis is the only mod (plus modlib)
Modlib is on top
(I also tried with stamina off)

error is following
![error_tweak](https://user-images.githubusercontent.com/3905307/80914142-0579e080-8d8d-11ea-8fa9-441e62d1864a.PNG)

Hope it helps!

Thanks!

**Comment by wfswanepoel** [comment]
For now the master version does not support BETA.
Go to: https://github.com/wfswanepoel/BannerlordTweaks
and https://github.com/wfswanepoel/ModLib

download those from the release zip file and just replace it. IT should work

**Comment by mipen** [comment]
The beta version is (finally) finished!

**Comment by jimbitol** [comment]
Thank you!!!
