### ISSUE TITLE
Crashing when Party size option is enabled

### ISSUE THREAD

**Issue by TheNog01** [mipen/BannerlordTweaks#82]
The main reason I wanted this mod was for the Steward/Leadership option for your party size, and having it enabled crashes my game...

**Comment by mipen** [comment]
Are you receiving an error message when the game crashes?

**Comment by TheNog01** [comment]
Yes it only crashes when I have the party size feature enabled and it states that when it crashes.

**Comment by mipen** [comment]
Can you please post an image of the error message for me? I need some details so I can figure out what is causing the issue.
