### ISSUE TITLE
BannerlordTweaks greyed out on mod selection

### ISSUE THREAD

**Issue by thecrazy13** [mipen/BannerlordTweaks#84]
Attempted restarts, reinstalling, updating all mods, playing without any other mods. Might be an issue with FixedLauncher, not sure, but the mod is only able to run when entirely on its own.
MODLIB IS INSTALLED AND ACTIVE
I am going to keep reposting this until I know the real issue behind it.

**Comment by mipen** [comment]
I assume that you are running fixed launcher. When I first installed it I had the same issue but it resolved itself by activating ModLib and restarting the launcher. Unfortunately this isn't a bug caused by Bannerlord Tweaks - it is the launcher. As such, I cannot offer anymore than what worked for me. Try the game without fixed launcher is everything else fails and see if that works.

**Comment by thecrazy13** [comment]
unfortunately it seems that fixedlauncher is necessary to run the launcher with BannerLordTweaks active
It's probably an issue that would have to be fixed on fixedlauncher's end, this is very frustrating.

**Comment by koyteck** [comment]
Are u sure?
So should i repost it on FixedLauncher repo?
Is it another way/launcher to fix it?

**Comment by thecrazy13** [comment]
probably, I have yet to manage to actually get the launcher to start with BannerlordTweaks enabled by FixedLauncher not enabled
so it's hit or miss on whether or not that is the actual issue

**Comment by mipen** [comment]
Give this launcher a try:
https://www.nexusmods.com/mountandblade2bannerlord/mods/265
I think of any way Bannerlord Tweaks would be messing with the launcher, I haven't done anything different than the official mods themselves. The only thing I can think is that the launcher isn't registering that ModLib is active, thus not allowing Tweaks to be enabled.

**Comment by thecrazy13** [comment]
![image](https://user-images.githubusercontent.com/23746741/81408281-f1c2d700-910a-11ea-9ab4-0712bee7dd56.png)
managed to get it to start with both, resulted in this crash report

**Comment by mipen** [comment]
The version of the mod you're using is outdated. You'll need to upgrade to the latest version on the nexus. If you're just using the base version of the game grab the 1.3.4 version of the mod. If you're using the beta version of the game, grab the 1.4 version of the mod.
