### ISSUE TITLE
Error Initialising Bannerlord Tweaks - details inside

### ISSUE THREAD

**Issue by koyteck** [mipen/BannerlordTweaks#85]
![png1](https://user-images.githubusercontent.com/7686546/81228251-11181200-8fee-11ea-8562-dd3e1b48ce53.PNG)
I tried with newest modlib and tweaks, etc. fixed lancher .
Ofc all dll files ublocked.
Ideas?

**Comment by mipen** [comment]
Thanks for the report. Looks like the hotfix broke that part of the mod. Fixed in the latest update.
