### ISSUE TITLE
Integrate native fixes into Community Patch

### ISSUE THREAD

**Issue by Tyler-IN** [mipen/BannerlordTweaks#9]
Would you be interested in collaborating to integrate the native fixes in this mod into the Community Patch mod?

https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/

**Comment by Tyler-IN** [comment]
Hello? I got a forum reply from you, but you didn't actually say yes or no, just that only one fix would apply.

**Comment by mipen** [comment]
Hi, looks like the mercenary contract bug has been fixed in the vanilla game. Other fixes in this mod are dependant on properties included in this mod, so for now I think I will have to opt out, sorry :(

**Comment by Tyler-IN** [comment]
Community Patch mod intends to be backwards compatible with previous versions.

Can we reference the fix you have anyway?

**Comment by Tyler-IN** [comment]
@mipen ?
