### ISSUE TITLE
HarmonyException

### ISSUE THREAD

**Issue by martinsir** [mipen/BannerlordTweaks#95]
Screenshot dialogbox added 

![errorHarmonyException](https://user-images.githubusercontent.com/4112720/81351485-bac9d280-90c4-11ea-8cb6-03b50fd57615.png)

**Comment by MiCLeal** [comment]
What version of the game and mod are you using?

**Comment by Rymi101** [comment]
I have the same issue. Bannerlord tweaks ver. 1.1.7.228.....
native ver. 1.3.0

**Comment by joshimoo** [comment]
We changed our versioning system to reflect the supported bannerlord version.
You will need to update to 1.3.x have a look at nexus, we will be releasing 1.3.4 soon for the stable release.

**Comment by joshimoo** [comment]
We have released 1.3.4 for the stable build, we will shortly release 1.4.0 for the new beta build.
Please update to the appropriate version :)
