### ISSUE TITLE
Compatability Issue: Menu Option Empty

### ISSUE THREAD

**Issue by garyaolz** [mipen/BannerlordTweaks#99]
Mod version 1.3.3, game version main branch 1.3.0.

If the game is loaded with BannerlordTweaks and any other mod, the Mod Option page for BannerlordTweaks is then empty. 

![20200508120815_1](https://user-images.githubusercontent.com/65004008/81371340-2d20ce00-912a-11ea-9714-f5bfd27cb0ba.jpg)

![20200508124941_1](https://user-images.githubusercontent.com/65004008/81371434-68230180-912a-11ea-9186-2226c828a493.jpg)

**Comment by garyaolz** [comment]
So I did some more testing, the tweak effects are still in place, it's just the menu page not showing

**Comment by wfswanepoel** [comment]
yes, this has nothing to do with Modlib or BannerlordTweaks. The mods have been updated and it is working. The other mods that are using Modlib requires an update.
